vlib work
vcom -2008 ../src/types.vhd
vcom -2008 ../src/logic/ALU.vhd
vcom -2008 ../simu/tbs/ALU_tb.vhd
vcom -2008 ../src/control_unit/decoder.vhd
vcom -2008 ../simu/tbs/decoder_tb.vhd
vcom -2008 ../src/data/instruction_memory_uart_int.vhd
vcom -2008 ../src/data/instruction_memory_uart.vhd
vcom -2008 ../src/data/memory.vhd
vcom -2008 ../simu/tbs/memory_tb.vhd
vcom -2008 ../src/utils/mux.vhd
vcom -2008 ../simu/tbs/mux_tb.vhd
vcom -2008 ../src/utils/sign_extender.vhd
vcom -2008 ../src/control_unit/pc_manager.vhd
vcom -2008 ../simu/tbs/pc_manager_tb.vhd
vcom -2008 ../src/data/registers.vhd
vcom -2008 ../src/processing_unit/processing_unit_basic.vhd
vcom -2008 ../simu/tbs/processing_unit_basic_tb.vhd
vcom -2008 ../src/processing_unit/processing_unit.vhd
vcom -2008 ../simu/tbs/processing_unit_tb.vhd
vcom -2008 ../src/utils/fdiv.vhd
vcom -2008 ../src/uart/uart_tx.vhd
vcom -2008 ../src/uart/uart_rx.vhd
vcom -2008 ../src/uart/uart_device.vhd
vcom -2008 ../src/interrupt/vector_int_controller.vhd
vcom -2008 ../src/data/instruction_memory.vhd
vcom -2008 ../src/control_unit/proc_state_reg.vhd
vcom -2008 ../src/processor_basic.vhd
vcom -2008 ../simu/tbs/processor_basic_tb.vhd
vcom -2008 ../src/data/instruction_memory_IRQ.vhd
vcom -2008 ../src/processor.vhd
vcom -2008 ../simu/tbs/PSR_tb.vhd
vcom -2008 ../simu/tbs/registers_tb.vhd
vcom -2008 ../simu/tbs/sign_extender_tb.vhd
vcom -2008 ../src/board/seveng_seg.vhd
vcom -2008 ../src/top_level.vhd
vcom -2008 ../simu/tbs/uart_tx_tb.vhd
vcom -2008 ../simu/tbs/vector_int_controller_tb.vhd
