standard = "2008"

[libraries]
# Use defaultlib instead of 'work' for all files
defaultlib.files = [
    "src/*.vhd",        # All source files including types.vhd
    "src/*/*.vhd",      # All source files including types.vhd
    "simu/tbs/*.vhd"    # All testbench files
]

[lint]
unused = 'error'
unnecessary_work_library = false
